# Generated by Django 5.1.2 on 2024-11-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0004_alter_exercise_table_alter_muscle_table'),
        ('WorkoutSet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('equipment_type', models.CharField(choices=[('free_weight', 'Free Weight'), ('machine', 'Machine')], default='free_weight', max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_items', to='Exercises.exercise')),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_items', to='WorkoutSet.workoutset')),
            ],
            options={
                'db_table': 'WorkoutItem',
            },
        ),
    ]
