# Generated by Django 5.1.2 on 2024-11-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutSet', '0002_workoutitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='exercises',
        ),
    ]
