# Generated by Django 5.1.4 on 2024-12-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Muscles/"),
                ),
            ],
            options={
                "db_table": "Muscle",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("gif", models.ImageField(blank=True, null=True, upload_to="gifs/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("flexibility", "Flexibility"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "muscle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="Exercises.muscle",
                    ),
                ),
            ],
            options={
                "db_table": "Exercise",
            },
        ),
    ]
