# Generated by Django 5.1.2 on 2024-11-10 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0002_exercise_allowed_weights_free_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='allowed_weights_free_weight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=4), blank=True, default=[2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25, 27.5, 30, 32.5, 35, 37.5, 40, 42.5, 45, 47.5, 50], size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='allowed_weights_machine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=['1 bar', '2 bar', '3 bar', '4 bar', '5 bar', '6 bar', '7 bar', '8 bar', '9 bar', '10 bar'], size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='gifs/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
