# Generated by Django 5.1.2 on 2024-11-10 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0004_alter_exercise_table_alter_muscle_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='allowed_weights_machine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], size=None),
        ),
    ]
