# Generated by Django 5.1.2 on 2024-11-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0005_alter_exercise_allowed_weights_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='allowed_weights_free_weight',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='allowed_weights_machine',
        ),
    ]
