# Generated by Django 5.1.2 on 2024-11-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_users_name_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
