# Generated by Django 5.1.2 on 2024-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_passwordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
